# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b270ced534f75b5c202548ec884c8b7426e88f366339a558e395e6de059a06775f4a3bbd85b9af34dddc5af6c98a275cc45bd311a34e9e24ca5f249927867b57

test:
  secret_key_base: 6c5bccf2126e9db6a18c1de8ac3a9525a76151a2652563d8d06043b915b3b192e393fd8960d726b5d760bb9dcdc5e34d127720c0e922ef1a280c52284b97f47a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 286b4a40077fae3befd6d95ccbdaa5a09eb53d859ac22dd4f2a6ba5ccfa3f3bf9024a0b0f89ad72e4d09937a564a1ccfd5b4494cfd67d67a29d35cf45c2f675d
